<%@ Page Title="" Language="C#" MasterPageFile="~/Pages/MasterPage.Master" AutoEventWireup="true" CodeBehind="Chat.aspx.cs" Inherits="SignalChat.Pages.Chat" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css'>
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/material-design-icons/3.0.1/iconfont/material-icons.min.css'>
    <link href="/css/style.css" rel="stylesheet" />
    <div class="container">
        <div class="row no-gutters">
            <div class="col-md-4 border-right">
                <div class="settings-tray">

                    <img class="profile-image" src="/img/user_icon.png" alt="Profile img">
                    <h7>
                        <label style="font-weight: bold; color:#0b9923;" id="lblusername" runat="server" ></label>
                    </h7>
                    <span class="settings-tray--right">
                        <i class="material-icons" id="signout">cached</i>
                        <%--<i class="material-icons">menu</i>--%>
                    </span>
                </div>
                <div class="search-box">
                    <div class="input-wrapper">
                        <%--<i class="material-icons">search</i>
                        <input placeholder="Search here" type="text">--%>
                    </div>
                </div>
                <div id="newuseradd">
                </div>
            </div>
            <div class="col-md-8" id="chatbox">
                <div class="settings-tray">
                    <div class="friend-drawer no-gutters friend-drawer--grey">
                        <img class="profile-image" src="/img/user_icon.png" alt="">
                        <div class="text">
                            <h6><label style="font-weight: bold;" id="lblchatusername"></label></h6>
                        </div>
                        <span class="settings-tray--right">
                            <%--<i class="material-icons" >cached</i>
                            <i class="material-icons">message</i>
                            <i class="material-icons">menu</i>--%>
                        </span>
                    </div>
                </div>
                <div class="chat-panel">
                    <div id="discussions">
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <div class="chat-box-tray">
                                <i class="material-icons">sentiment_very_satisfied</i>
                                <input type="text" id="message" placeholder="Type your message here...">
                                <i class="material-icons" id="sendmessage">send</i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!--Script references. -->
    <!--Reference the jQuery library. -->
    <script src="/Scripts/jquery-3.4.1.min.js"></script>
    <!--Reference the SignalR library. -->
    <script src="/Scripts/jquery.signalR-2.2.2.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="/signalr/hubs"></script>
    <script src="/Scripts/script.js"></script>
    <!--Add script to update the page and send messages.-->
    <script src="/Scripts/jscrypto/ecdh.js"></script>
</asp:Content>
