<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Index.aspx.cs" Inherits="SignalChat.Index" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Signal Chat</title>
    <style type="text/css">
        .container {
            background-color: #99CCFF;
            border: thick solid #808080;
            padding: 20px;
            margin: 20px;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <div class="container">
            <span>Select user to start chat:</span>
            <select id="UserNameList" name="Username" style="width:200px ">
                <option>No one is here!</option>
            </select>
 
            <h1>
                <label id="lblusername"></label>
            </h1>
            <input type="text" id="message" />
            <input type="button" id="sendmessage" value="Send" />
            <input type="button" id="clearusers" value="Clear Users" />
            <input type="button" id="clearcache" value="Clear Cache" />
            <input type="button" id="signout" value="Sign Out" />
            <input type="hidden" id="displayname" />
            <ul id="discussion">
            </ul>
        </div>
        <!--Script references. -->
        <!--Reference the jQuery library. -->
        <script src="Scripts/jquery-3.4.1.min.js"></script>
        <!--Reference the SignalR library. -->
        <script src="Scripts/jquery.signalR-2.2.2.min.js"></script>
        <!--Reference the autogenerated SignalR hub script. -->
        <script src="/signalr/hubs"></script>
        <!--Add script to update the page and send messages.-->
        <script src="Scripts/jscrypto/ecdh.js"></script>
    </form>
</body>
</html>
